// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/obj.proto

package umamaheswari76

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ObjGrpcServiceClient is the client API for ObjGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjGrpcServiceClient interface {
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
}

type objGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObjGrpcServiceClient(cc grpc.ClientConnInterface) ObjGrpcServiceClient {
	return &objGrpcServiceClient{cc}
}

func (c *objGrpcServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/kv_grpc.ObjGrpcService/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjGrpcServiceServer is the server API for ObjGrpcService service.
// All implementations must embed UnimplementedObjGrpcServiceServer
// for forward compatibility
type ObjGrpcServiceServer interface {
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	mustEmbedUnimplementedObjGrpcServiceServer()
}

// UnimplementedObjGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedObjGrpcServiceServer struct {
}

func (UnimplementedObjGrpcServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedObjGrpcServiceServer) mustEmbedUnimplementedObjGrpcServiceServer() {}

// UnsafeObjGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjGrpcServiceServer will
// result in compilation errors.
type UnsafeObjGrpcServiceServer interface {
	mustEmbedUnimplementedObjGrpcServiceServer()
}

func RegisterObjGrpcServiceServer(s grpc.ServiceRegistrar, srv ObjGrpcServiceServer) {
	s.RegisterService(&ObjGrpcService_ServiceDesc, srv)
}

func _ObjGrpcService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjGrpcServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv_grpc.ObjGrpcService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjGrpcServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjGrpcService_ServiceDesc is the grpc.ServiceDesc for ObjGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kv_grpc.ObjGrpcService",
	HandlerType: (*ObjGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _ObjGrpcService_GetFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/obj.proto",
}
