// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/kv.proto

package umamaheswari76

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KvGrpcServiceClient is the client API for KvGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvGrpcServiceClient interface {
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
}

type kvGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKvGrpcServiceClient(cc grpc.ClientConnInterface) KvGrpcServiceClient {
	return &kvGrpcServiceClient{cc}
}

func (c *kvGrpcServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/kv_grpc.KvGrpcService/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvGrpcServiceServer is the server API for KvGrpcService service.
// All implementations must embed UnimplementedKvGrpcServiceServer
// for forward compatibility
type KvGrpcServiceServer interface {
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	mustEmbedUnimplementedKvGrpcServiceServer()
}

// UnimplementedKvGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKvGrpcServiceServer struct {
}

func (UnimplementedKvGrpcServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedKvGrpcServiceServer) mustEmbedUnimplementedKvGrpcServiceServer() {}

// UnsafeKvGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvGrpcServiceServer will
// result in compilation errors.
type UnsafeKvGrpcServiceServer interface {
	mustEmbedUnimplementedKvGrpcServiceServer()
}

func RegisterKvGrpcServiceServer(s grpc.ServiceRegistrar, srv KvGrpcServiceServer) {
	s.RegisterService(&KvGrpcService_ServiceDesc, srv)
}

func _KvGrpcService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvGrpcServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv_grpc.KvGrpcService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvGrpcServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KvGrpcService_ServiceDesc is the grpc.ServiceDesc for KvGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KvGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kv_grpc.KvGrpcService",
	HandlerType: (*KvGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _KvGrpcService_GetFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kv.proto",
}
